name: Build Flutter APK

on:
  push:
    branches: [ main, "رئيسي" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Setup Android Project
        run: |
          cp lib/main.dart /tmp/main.dart
          cp pubspec.yaml /tmp/pubspec.yaml
          flutter create --org com.dahshory.agri --project-name agri_app .
          cp /tmp/main.dart lib/main.dart
          cp /tmp/pubspec.yaml pubspec.yaml
          
          # تحديث إصدار كوتلن بشكل آمن داخل النظام المتوافق
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.22"/' android/build.gradle || true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        # السطر ده هو اللي بياخد المفتاح من الخزنة ويدخله في التطبيق وقت البناء
        run: flutter build apk --release --no-tree-shake-icons --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
